### ISSUE TITLE
Binding changes when using ch_funcs

### ISSUE THREAD

**Issue by sylvainbonnot** [i2mint/meshed#43]
The following code triggers an Assertion Error. Such errors happen a lot when using front.

```python
def foo(x, y, z="23"):
    return int(x) + int(y) * int(z)


def bar(res, other="stuff"):
    return f"{res=}, {other=}"

@code_to_dag
def dag():
    res = first_func(x, y, z)
    result = second_func(res, other)


dag = dag.ch_funcs(
    first_func=rm_params(foo, params_to_remove=("z",)),
    second_func=bar,
)

# AssertionError: some bind keys weren't found as function argnames: z
```

**Comment by thorwhalen** [comment]
Since the [7034e10 commit](https://github.com/i2mint/meshed/commit/7034e103b8d2e281f418323341fad218cc39743e), which made `.ch_funcs` more restrictive, the error reads now:

```
ValueError: You can only change the func of a `FuncNode` with another func if the signatures match.
	fn=FuncNode(x,y,z -> first_func -> res)
	Sig(fn.func)=<Sig (x, y, z)>
	Sig(func)=<Sig (x, y)>
```

This is not a bug, but a feature. 
In the example above, the modified `foo` that we want to use as our `first_func` doesn't have a `z` argument, but in the `dag`'s definition of `first_func` we require it. 
Therefore, we **should** raise an error here; though the original assertion error was not as helpful as the new one. 

But let's take this occasion to address a more subtle issue, say we didn't modify the `foo`.
Then we'd get:

```python
>>> dag = dag.ch_funcs(first_func=foo, second_func=bar)
ValueError                                Traceback (most recent call last)
...
ValueError: You can only change the func of a FuncNode with a another func if the signatures match.
	fn=FuncNode(x,y,z -> first_func -> res)
	Sig(fn.func)=<Sig (x, y, z)>
	Sig(func)=<Sig (x, y, z='23')>
```

Here we **do** have a `z`, but `ch_funcs` still complains because it has a default, and the existing placeholder function does not. **That** is probably **too** restrictive!

What's happening here is that the `DAG.ch_funcs`, which forwards to the `FuncNode.ch_funcs` method, requires the signatures of a replacement function to match the signature of the existing function **in the most restrictive sense**. 
This is a _good thing_ for robustness, since this will reduce the surprising buried bugs down the line. It's `explicit over implicit` ([zen of python](https://peps.python.org/pep-0020/)). But it's _not a good thing_ for flexibility and UX, as mentioned in [the issue](https://github.com/i2mint/meshed/issues/44) that made `ch_funcs` more restrictive. 

The ["Dag.ch_func and signature comparison"](https://github.com/i2mint/meshed/issues/45) issue brings up the need for control over this aspect.

**Comment by thorwhalen** [comment]
The above comment closes this issue.
